#include "glext_loader.h"

PFNGLACTIVETEXTUREPROC glActiveTextureEXT = nullptr;
PFNGLBINDBUFFERPROC  glBindBuffer = nullptr;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = nullptr;
PFNGLGENBUFFERSPROC glGenBuffers = nullptr;
PFNGLISBUFFERPROC glIsBuffer = nullptr;
PFNGLBUFFERDATAPROC glBufferData = nullptr;
PFNGLBUFFERSUBDATAPROC glBufferSubData = nullptr;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData = nullptr;
PFNGLMAPBUFFERPROC glMapBuffer = nullptr;
PFNGLUNMAPBUFFERPROC glUnmapBuffer = nullptr;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv = nullptr;
PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv = nullptr;

PFNGLATTACHSHADERPROC glAttachShader = nullptr;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation = nullptr;
PFNGLCOMPILESHADERPROC glCompileShader = nullptr;
PFNGLCREATEPROGRAMPROC glCreateProgram = nullptr;
PFNGLCREATESHADERPROC glCreateShader = nullptr;
PFNGLDELETEPROGRAMPROC glDeleteProgram = nullptr;
PFNGLDELETESHADERPROC glDeleteShader = nullptr;
PFNGLDETACHSHADERPROC glDetachShader = nullptr;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = nullptr;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = nullptr;
PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib = nullptr;
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform = nullptr;
PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders = nullptr;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation = nullptr;
PFNGLGETPROGRAMIVPROC glGetProgramiv = nullptr;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = nullptr;
PFNGLGETSHADERIVPROC glGetShaderiv = nullptr;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = nullptr;
PFNGLGETSHADERSOURCEPROC glGetShaderSource = nullptr;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = nullptr;
PFNGLGETUNIFORMFVPROC glGetUniformfv = nullptr;
PFNGLGETUNIFORMIVPROC glGetUniformiv = nullptr;
PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv = nullptr;
PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv = nullptr;
PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv = nullptr;
PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv = nullptr;
PFNGLISPROGRAMPROC glIsProgram = nullptr;
PFNGLISSHADERPROC glIsShader = nullptr;
PFNGLLINKPROGRAMPROC glLinkProgram = nullptr;
PFNGLSHADERSOURCEPROC glShaderSource = nullptr;
PFNGLUSEPROGRAMPROC glUseProgram = nullptr;

PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer = nullptr;
PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv = nullptr;
PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv = nullptr;
PFNGLVERTEXATTRIBPOINTERARBPROC glVertexAttribPointer = nullptr;
PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor = nullptr;

PFNGLBINDVERTEXARRAYPROC glBindVertexArray = nullptr;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays = nullptr;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = nullptr;
PFNGLISVERTEXARRAYPROC glIsVertexArray = nullptr;

PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex = nullptr;

PFNGLUNIFORM1FPROC glUniform1f = nullptr;
PFNGLUNIFORM2FPROC glUniform2f = nullptr;
PFNGLUNIFORM3FPROC glUniform3f = nullptr;
PFNGLUNIFORM4FPROC glUniform4f = nullptr;
PFNGLUNIFORM1IPROC glUniform1i = nullptr;
PFNGLUNIFORM2IPROC glUniform2i = nullptr;
PFNGLUNIFORM3IPROC glUniform3i = nullptr;
PFNGLUNIFORM4IPROC glUniform4i = nullptr;

PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced = nullptr;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced = nullptr;

#define GL_GET_FUNC( funcproto, funcname ) \
    funcname = (funcproto)SDL_GL_GetProcAddress( #funcname ); \
    if( !funcname ) \
        return false;

bool init_ogl_exts( )
{
	glActiveTextureEXT = (PFNGLACTIVETEXTUREPROC)SDL_GL_GetProcAddress( "glActiveTexture" );
	if( !glActiveTextureEXT )
		return false;
    
    GL_GET_FUNC( PFNGLBINDBUFFERPROC, glBindBuffer);
    GL_GET_FUNC( PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
    GL_GET_FUNC( PFNGLGENBUFFERSPROC, glGenBuffers);
    GL_GET_FUNC( PFNGLISBUFFERPROC, glIsBuffer);
    GL_GET_FUNC( PFNGLBUFFERDATAPROC, glBufferData);
    GL_GET_FUNC( PFNGLBUFFERSUBDATAPROC, glBufferSubData);
    GL_GET_FUNC( PFNGLGETBUFFERSUBDATAPROC, glGetBufferSubData);
    GL_GET_FUNC( PFNGLMAPBUFFERPROC, glMapBuffer);
    GL_GET_FUNC( PFNGLUNMAPBUFFERPROC, glUnmapBuffer);
    GL_GET_FUNC( PFNGLGETBUFFERPARAMETERIVPROC, glGetBufferParameteriv);
    GL_GET_FUNC( PFNGLGETBUFFERPOINTERVPROC, glGetBufferPointerv);

    GL_GET_FUNC( PFNGLATTACHSHADERPROC, glAttachShader);
    GL_GET_FUNC( PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation);
    GL_GET_FUNC( PFNGLCOMPILESHADERPROC, glCompileShader);
    GL_GET_FUNC( PFNGLCREATEPROGRAMPROC, glCreateProgram);
    GL_GET_FUNC( PFNGLCREATESHADERPROC, glCreateShader);
    GL_GET_FUNC( PFNGLDELETEPROGRAMPROC, glDeleteProgram);
    GL_GET_FUNC( PFNGLDELETESHADERPROC, glDeleteShader);
    GL_GET_FUNC( PFNGLDETACHSHADERPROC, glDetachShader);
    GL_GET_FUNC( PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray);
    GL_GET_FUNC( PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
    GL_GET_FUNC( PFNGLGETACTIVEATTRIBPROC, glGetActiveAttrib);
    GL_GET_FUNC( PFNGLGETACTIVEUNIFORMPROC, glGetActiveUniform);
    GL_GET_FUNC( PFNGLGETATTACHEDSHADERSPROC, glGetAttachedShaders);
    GL_GET_FUNC( PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation);
    GL_GET_FUNC( PFNGLGETPROGRAMIVPROC, glGetProgramiv);
    GL_GET_FUNC( PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
    GL_GET_FUNC( PFNGLGETSHADERIVPROC, glGetShaderiv);
    GL_GET_FUNC( PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
    GL_GET_FUNC( PFNGLGETSHADERSOURCEPROC, glGetShaderSource);
    GL_GET_FUNC( PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
    GL_GET_FUNC( PFNGLGETUNIFORMFVPROC, glGetUniformfv);
    GL_GET_FUNC( PFNGLGETUNIFORMIVPROC, glGetUniformiv);
    GL_GET_FUNC( PFNGLGETVERTEXATTRIBDVPROC, glGetVertexAttribdv);
    GL_GET_FUNC( PFNGLGETVERTEXATTRIBFVPROC, glGetVertexAttribfv);
    GL_GET_FUNC( PFNGLGETVERTEXATTRIBIVPROC, glGetVertexAttribiv);
    GL_GET_FUNC( PFNGLGETVERTEXATTRIBPOINTERVPROC, glGetVertexAttribPointerv);
    GL_GET_FUNC( PFNGLISPROGRAMPROC, glIsProgram);
    GL_GET_FUNC( PFNGLISSHADERPROC, glIsShader);
    GL_GET_FUNC( PFNGLLINKPROGRAMPROC, glLinkProgram);
    GL_GET_FUNC( PFNGLSHADERSOURCEPROC, glShaderSource);
    GL_GET_FUNC( PFNGLUSEPROGRAMPROC, glUseProgram);

    GL_GET_FUNC( PFNGLVERTEXATTRIBIPOINTERPROC, glVertexAttribIPointer);
    GL_GET_FUNC( PFNGLGETVERTEXATTRIBIIVPROC, glGetVertexAttribIiv);
    GL_GET_FUNC( PFNGLGETVERTEXATTRIBIUIVPROC, glGetVertexAttribIuiv);
    GL_GET_FUNC( PFNGLVERTEXATTRIBPOINTERARBPROC, glVertexAttribPointer);
    GL_GET_FUNC( PFNGLVERTEXATTRIBDIVISORPROC, glVertexAttribDivisor);

    GL_GET_FUNC( PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
    GL_GET_FUNC( PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays);
    GL_GET_FUNC( PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
    GL_GET_FUNC( PFNGLISVERTEXARRAYPROC, glIsVertexArray);

    GL_GET_FUNC( PFNGLPRIMITIVERESTARTINDEXPROC, glPrimitiveRestartIndex);

    GL_GET_FUNC( PFNGLUNIFORM1FPROC, glUniform1f);
    GL_GET_FUNC( PFNGLUNIFORM2FPROC, glUniform2f);
    GL_GET_FUNC( PFNGLUNIFORM3FPROC, glUniform3f);
    GL_GET_FUNC( PFNGLUNIFORM4FPROC, glUniform4f);
    GL_GET_FUNC( PFNGLUNIFORM1IPROC, glUniform1i);
    GL_GET_FUNC( PFNGLUNIFORM2IPROC, glUniform2i);
    GL_GET_FUNC( PFNGLUNIFORM3IPROC, glUniform3i);
    GL_GET_FUNC( PFNGLUNIFORM4IPROC, glUniform4i);

    GL_GET_FUNC( PFNGLDRAWARRAYSINSTANCEDPROC, glDrawArraysInstanced);
    GL_GET_FUNC( PFNGLDRAWELEMENTSINSTANCEDPROC, glDrawElementsInstanced);

    return true;
}